sudo: false
language: ruby
cache: bundler
before_install: gem update bundler
matrix:
  include:
    - rvm: 2.1.0
    - rvm: 2.1.10
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: rbx-3
  fast_finish: true
script: bundle exec rake
addons:
    code_climate:
        repo_token: 6896a20297dac7ea23f4786a3e91357ed5714984a14662892389722c3aeaf085